### ISSUE TITLE
💥Major Release: Algodex SDK 2.X.X

### ISSUE THREAD

**Issue by PhearZero** [algodex/algodex-sdk#111]
# ℹ Overview

Major refactor of `@algodex/algodex-sdk` in order to support multiple wallet services and introduce [ALM/QA](https://github.com/algodex/developer.algodex.com/blob/main/VISION.md). 

This refactor also introduces state in the form of constructors. These constructors should help developers interact with the Algodex Ecosystem. ~~The refactor is backwards compatible with v1 sdk until further notice~~. This stages for a future "plugin" model where multiple contract sdks can share the same API interface.

- [x] #72 
- [x] ✨ Feature: Add Order state to SDK from React
- [x] #125 
- [x] 🚨 Chore: Fix the rest of the lint errors
- [x] 🚀 Chore: Release with sematic-release
